### ISSUE TITLE
KI - Use Case | Upload der neu erzeugten Bilder

### ISSUE THREAD

**Issue by Jonasstemme** [vitrum-connect/5gla-ai-spectral-unmixing#4]
**Beschreibung**
Als Wissenschaftler möchte ich, dass die generierten Bilder zurück in die DB geschrieben werden, damit ich diese in QGIS als Layer einbinden kann.

**Akzeptanzkriterien**

Die User Story gilt als erfolgreich umgesetzt, wenn:

- die Bilder zurück in den S3-Speicher geschrieben werden,
- die Bilder entsprechend benannt werden,
- die Bilder ein Zeitstempel erhalten.
- Im Titel oder in der Beschreibung sollten die Metadaten erkenntlich sein, dass der Endnutzer nachvollziehen kann, aus welcher Aufnahme dieser Datensatz stammt.

**Comment by Chromeggs** [comment]
Moin @hwuebben ,
Kannst du etwas zum Fortschritt dieser UserStory sagen?
Und das Ausliefrungsdatum liegt noch auf dem 18.10., müsste also ggf. angepasst werden, sofern es länger dauert.
Thx
Ben

**Comment by hwuebben** [comment]
moin @Chromeggs,
wird ab Montag angegangen.
VG

**Comment by hwuebben** [comment]
Abstimmung mit sascha notwendig und bereits geplant

**Comment by Chromeggs** [comment]
Moin @hwuebben und @Jonasstemme ,
Bitte kommeniert hier die News dazu und definiert das voraussichtliche Ausliferungsdatum dieser UserStory neu.
Meine Meinung außerdem dazu: Da wir nun in einem sehr kurzen Zeitfenster arbeiten, können wir es uns eigentlich nicht mehr leisten, Aufgaben wochenweise weiterzuschieben.
Wie seht ihr das?
LG Ben

**Comment by hwuebben** [comment]
Die Anbindung steht mittlerweile.

**Comment by Chromeggs** [comment]
Moin @Jonasstemme und @hwuebben,
Könnt ihr mal bitte das Datum der vorrausichtlichen Auslieferung dieser UserStory anpassen? (liegt deutlich in der Vergangenheit, und hatte ich letzte Woche auch schon einmal reklamiert...)
Thx
Ben
